# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/jfa49/180304_vdma_test_change/vdma_test.srcs/sources_1/bd/dma_design_1/ip/dma_design_1_axi_vdma_0_0/dma_design_1_axi_vdma_0_0.xci
# IP: The module: 'dma_design_1_axi_vdma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jfa49/180304_vdma_test_change/vdma_test.srcs/sources_1/bd/dma_design_1/ip/dma_design_1_axi_vdma_0_0/dma_design_1_axi_vdma_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_design_1_axi_vdma_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/jfa49/180304_vdma_test_change/vdma_test.srcs/sources_1/bd/dma_design_1/ip/dma_design_1_axi_vdma_0_0/dma_design_1_axi_vdma_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_design_1_axi_vdma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/jfa49/180304_vdma_test_change/vdma_test.srcs/sources_1/bd/dma_design_1/ip/dma_design_1_axi_vdma_0_0/dma_design_1_axi_vdma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_design_1_axi_vdma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/jfa49/180304_vdma_test_change/vdma_test.srcs/sources_1/bd/dma_design_1/ip/dma_design_1_axi_vdma_0_0/dma_design_1_axi_vdma_0_0.xci
# IP: The module: 'dma_design_1_axi_vdma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jfa49/180304_vdma_test_change/vdma_test.srcs/sources_1/bd/dma_design_1/ip/dma_design_1_axi_vdma_0_0/dma_design_1_axi_vdma_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_design_1_axi_vdma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/jfa49/180304_vdma_test_change/vdma_test.srcs/sources_1/bd/dma_design_1/ip/dma_design_1_axi_vdma_0_0/dma_design_1_axi_vdma_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_design_1_axi_vdma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/jfa49/180304_vdma_test_change/vdma_test.srcs/sources_1/bd/dma_design_1/ip/dma_design_1_axi_vdma_0_0/dma_design_1_axi_vdma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_design_1_axi_vdma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
