# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/yangjiel/Desktop/180305_vdma_test_M2M3_change/180305_vdma_test_M2M3_change.cache/wt [current_project]
set_property parent.project_path C:/Users/yangjiel/Desktop/180305_vdma_test_M2M3_change/180305_vdma_test_M2M3_change.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths c:/Users/yangjiel/Desktop/VGA_mem_mapped-master/project_audio [current_project]
set_property ip_output_repo c:/Users/yangjiel/Desktop/180305_vdma_test_M2M3_change/180305_vdma_test_M2M3_change.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib C:/Users/yangjiel/Desktop/180305_vdma_test_M2M3_change/180305_vdma_test_M2M3_change.srcs/sources_1/imports/hdl/dma_design_1_wrapper.v
add_files C:/Users/yangjiel/Desktop/180305_vdma_test_M2M3_change/180305_vdma_test_M2M3_change.srcs/sources_1/bd/dma_design_1/dma_design_1.bd
set_property used_in_implementation false [get_files -all c:/Users/yangjiel/Desktop/180305_vdma_test_M2M3_change/180305_vdma_test_M2M3_change.srcs/sources_1/bd/dma_design_1/ip/dma_design_1_axi_smc_0/bd_0/ip/ip_5/bd_a967_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yangjiel/Desktop/180305_vdma_test_M2M3_change/180305_vdma_test_M2M3_change.srcs/sources_1/bd/dma_design_1/ip/dma_design_1_axi_smc_0/bd_0/ip/ip_8/bd_a967_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yangjiel/Desktop/180305_vdma_test_M2M3_change/180305_vdma_test_M2M3_change.srcs/sources_1/bd/dma_design_1/ip/dma_design_1_axi_smc_0/bd_0/ip/ip_6/bd_a967_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yangjiel/Desktop/180305_vdma_test_M2M3_change/180305_vdma_test_M2M3_change.srcs/sources_1/bd/dma_design_1/ip/dma_design_1_axi_smc_0/bd_0/ip/ip_7/bd_a967_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yangjiel/Desktop/180305_vdma_test_M2M3_change/180305_vdma_test_M2M3_change.srcs/sources_1/bd/dma_design_1/ip/dma_design_1_axi_smc_0/bd_0/ip/ip_1/bd_a967_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yangjiel/Desktop/180305_vdma_test_M2M3_change/180305_vdma_test_M2M3_change.srcs/sources_1/bd/dma_design_1/ip/dma_design_1_axi_smc_0/bd_0/ip/ip_1/bd_a967_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yangjiel/Desktop/180305_vdma_test_M2M3_change/180305_vdma_test_M2M3_change.srcs/sources_1/bd/dma_design_1/ip/dma_design_1_axi_smc_0/ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yangjiel/Desktop/180305_vdma_test_M2M3_change/180305_vdma_test_M2M3_change.srcs/sources_1/bd/dma_design_1/ip/dma_design_1_axi_vdma_0_0/dma_design_1_axi_vdma_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yangjiel/Desktop/180305_vdma_test_M2M3_change/180305_vdma_test_M2M3_change.srcs/sources_1/bd/dma_design_1/ip/dma_design_1_axi_vdma_0_0/dma_design_1_axi_vdma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yangjiel/Desktop/180305_vdma_test_M2M3_change/180305_vdma_test_M2M3_change.srcs/sources_1/bd/dma_design_1/ip/dma_design_1_axi_vdma_0_0/dma_design_1_axi_vdma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yangjiel/Desktop/180305_vdma_test_M2M3_change/180305_vdma_test_M2M3_change.srcs/sources_1/bd/dma_design_1/ip/dma_design_1_proc_sys_reset_0_0/dma_design_1_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yangjiel/Desktop/180305_vdma_test_M2M3_change/180305_vdma_test_M2M3_change.srcs/sources_1/bd/dma_design_1/ip/dma_design_1_proc_sys_reset_0_0/dma_design_1_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yangjiel/Desktop/180305_vdma_test_M2M3_change/180305_vdma_test_M2M3_change.srcs/sources_1/bd/dma_design_1/ip/dma_design_1_proc_sys_reset_0_0/dma_design_1_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yangjiel/Desktop/180305_vdma_test_M2M3_change/180305_vdma_test_M2M3_change.srcs/sources_1/bd/dma_design_1/ip/dma_design_1_processing_system7_0_0/dma_design_1_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yangjiel/Desktop/180305_vdma_test_M2M3_change/180305_vdma_test_M2M3_change.srcs/sources_1/bd/dma_design_1/ip/dma_design_1_rst_ps7_0_100M_0/dma_design_1_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yangjiel/Desktop/180305_vdma_test_M2M3_change/180305_vdma_test_M2M3_change.srcs/sources_1/bd/dma_design_1/ip/dma_design_1_rst_ps7_0_100M_0/dma_design_1_rst_ps7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yangjiel/Desktop/180305_vdma_test_M2M3_change/180305_vdma_test_M2M3_change.srcs/sources_1/bd/dma_design_1/ip/dma_design_1_rst_ps7_0_100M_0/dma_design_1_rst_ps7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yangjiel/Desktop/180305_vdma_test_M2M3_change/180305_vdma_test_M2M3_change.srcs/sources_1/bd/dma_design_1/ip/dma_design_1_v_axi4s_vid_out_0_0/dma_design_1_v_axi4s_vid_out_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yangjiel/Desktop/180305_vdma_test_M2M3_change/180305_vdma_test_M2M3_change.srcs/sources_1/bd/dma_design_1/ip/dma_design_1_v_axi4s_vid_out_0_0/dma_design_1_v_axi4s_vid_out_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yangjiel/Desktop/180305_vdma_test_M2M3_change/180305_vdma_test_M2M3_change.srcs/sources_1/bd/dma_design_1/ip/dma_design_1_v_tc_0_0/dma_design_1_v_tc_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yangjiel/Desktop/180305_vdma_test_M2M3_change/180305_vdma_test_M2M3_change.srcs/sources_1/bd/dma_design_1/ip/dma_design_1_v_tc_0_0/dma_design_1_v_tc_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yangjiel/Desktop/180305_vdma_test_M2M3_change/180305_vdma_test_M2M3_change.srcs/sources_1/bd/dma_design_1/ip/dma_design_1_xbar_0/dma_design_1_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yangjiel/Desktop/180305_vdma_test_M2M3_change/180305_vdma_test_M2M3_change.srcs/sources_1/bd/dma_design_1/ip/dma_design_1_axi_gpio_0_0/dma_design_1_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yangjiel/Desktop/180305_vdma_test_M2M3_change/180305_vdma_test_M2M3_change.srcs/sources_1/bd/dma_design_1/ip/dma_design_1_axi_gpio_0_0/dma_design_1_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yangjiel/Desktop/180305_vdma_test_M2M3_change/180305_vdma_test_M2M3_change.srcs/sources_1/bd/dma_design_1/ip/dma_design_1_axi_gpio_0_0/dma_design_1_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yangjiel/Desktop/180305_vdma_test_M2M3_change/180305_vdma_test_M2M3_change.srcs/sources_1/bd/dma_design_1/ip/dma_design_1_axi_gpio_1_0/dma_design_1_axi_gpio_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yangjiel/Desktop/180305_vdma_test_M2M3_change/180305_vdma_test_M2M3_change.srcs/sources_1/bd/dma_design_1/ip/dma_design_1_axi_gpio_1_0/dma_design_1_axi_gpio_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yangjiel/Desktop/180305_vdma_test_M2M3_change/180305_vdma_test_M2M3_change.srcs/sources_1/bd/dma_design_1/ip/dma_design_1_axi_gpio_1_0/dma_design_1_axi_gpio_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yangjiel/Desktop/180305_vdma_test_M2M3_change/180305_vdma_test_M2M3_change.srcs/sources_1/bd/dma_design_1/ip/dma_design_1_axi_gpio_2_3/dma_design_1_axi_gpio_2_3_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yangjiel/Desktop/180305_vdma_test_M2M3_change/180305_vdma_test_M2M3_change.srcs/sources_1/bd/dma_design_1/ip/dma_design_1_axi_gpio_2_3/dma_design_1_axi_gpio_2_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yangjiel/Desktop/180305_vdma_test_M2M3_change/180305_vdma_test_M2M3_change.srcs/sources_1/bd/dma_design_1/ip/dma_design_1_axi_gpio_2_3/dma_design_1_axi_gpio_2_3.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yangjiel/Desktop/180305_vdma_test_M2M3_change/180305_vdma_test_M2M3_change.srcs/sources_1/bd/dma_design_1/ip/dma_design_1_auto_pc_0/dma_design_1_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/yangjiel/Desktop/180305_vdma_test_M2M3_change/180305_vdma_test_M2M3_change.srcs/sources_1/bd/dma_design_1/dma_design_1_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/yangjiel/Desktop/180305_vdma_test_M2M3_change/180305_vdma_test_M2M3_change.srcs/constrs_1/imports/scripts/zedboard_master_XDC_RevC_D_v3.xdc
set_property used_in_implementation false [get_files C:/Users/yangjiel/Desktop/180305_vdma_test_M2M3_change/180305_vdma_test_M2M3_change.srcs/constrs_1/imports/scripts/zedboard_master_XDC_RevC_D_v3.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top dma_design_1_wrapper -part xc7z020clg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef dma_design_1_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file dma_design_1_wrapper_utilization_synth.rpt -pb dma_design_1_wrapper_utilization_synth.pb"
