# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/scripts/zedboard_master_XDC_RevC_D_v3.xdc

# Block Designs: bd/dma_design_1/dma_design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_design_1 || ORIG_REF_NAME==dma_design_1} -quiet] -quiet

# IP: bd/dma_design_1/ip/dma_design_1_axi_smc_0/dma_design_1_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_design_1_axi_smc_0 || ORIG_REF_NAME==dma_design_1_axi_smc_0} -quiet] -quiet

# IP: bd/dma_design_1/ip/dma_design_1_axi_vdma_0_0/dma_design_1_axi_vdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_design_1_axi_vdma_0_0 || ORIG_REF_NAME==dma_design_1_axi_vdma_0_0} -quiet] -quiet

# IP: bd/dma_design_1/ip/dma_design_1_proc_sys_reset_0_0/dma_design_1_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_design_1_proc_sys_reset_0_0 || ORIG_REF_NAME==dma_design_1_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/dma_design_1/ip/dma_design_1_processing_system7_0_0/dma_design_1_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_design_1_processing_system7_0_0 || ORIG_REF_NAME==dma_design_1_processing_system7_0_0} -quiet] -quiet

# IP: bd/dma_design_1/ip/dma_design_1_ps7_0_axi_periph_0/dma_design_1_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_design_1_ps7_0_axi_periph_0 || ORIG_REF_NAME==dma_design_1_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/dma_design_1/ip/dma_design_1_rst_ps7_0_100M_0/dma_design_1_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_design_1_rst_ps7_0_100M_0 || ORIG_REF_NAME==dma_design_1_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/dma_design_1/ip/dma_design_1_v_axi4s_vid_out_0_0/dma_design_1_v_axi4s_vid_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_design_1_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==dma_design_1_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: bd/dma_design_1/ip/dma_design_1_v_tc_0_0/dma_design_1_v_tc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_design_1_v_tc_0_0 || ORIG_REF_NAME==dma_design_1_v_tc_0_0} -quiet] -quiet

# IP: bd/dma_design_1/ip/dma_design_1_vga_logic_0_0/dma_design_1_vga_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_design_1_vga_logic_0_0 || ORIG_REF_NAME==dma_design_1_vga_logic_0_0} -quiet] -quiet

# IP: bd/dma_design_1/ip/dma_design_1_xlconcat_0_0/dma_design_1_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_design_1_xlconcat_0_0 || ORIG_REF_NAME==dma_design_1_xlconcat_0_0} -quiet] -quiet

# IP: bd/dma_design_1/ip/dma_design_1_xlconstant_0_0/dma_design_1_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_design_1_xlconstant_0_0 || ORIG_REF_NAME==dma_design_1_xlconstant_0_0} -quiet] -quiet

# IP: bd/dma_design_1/ip/dma_design_1_xbar_0/dma_design_1_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_design_1_xbar_0 || ORIG_REF_NAME==dma_design_1_xbar_0} -quiet] -quiet

# IP: bd/dma_design_1/ip/dma_design_1_axi_gpio_0_0/dma_design_1_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_design_1_axi_gpio_0_0 || ORIG_REF_NAME==dma_design_1_axi_gpio_0_0} -quiet] -quiet

# IP: bd/dma_design_1/ip/dma_design_1_LSFR_0_0/dma_design_1_LSFR_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_design_1_LSFR_0_0 || ORIG_REF_NAME==dma_design_1_LSFR_0_0} -quiet] -quiet

# IP: bd/dma_design_1/ip/dma_design_1_axi_gpio_1_0/dma_design_1_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_design_1_axi_gpio_1_0 || ORIG_REF_NAME==dma_design_1_axi_gpio_1_0} -quiet] -quiet

# IP: bd/dma_design_1/ip/dma_design_1_axi_gpio_2_3/dma_design_1_axi_gpio_2_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_design_1_axi_gpio_2_3 || ORIG_REF_NAME==dma_design_1_axi_gpio_2_3} -quiet] -quiet

# IP: bd/dma_design_1/ip/dma_design_1_audio_testbench_0_0/dma_design_1_audio_testbench_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_design_1_audio_testbench_0_0 || ORIG_REF_NAME==dma_design_1_audio_testbench_0_0} -quiet] -quiet

# IP: bd/dma_design_1/ip/dma_design_1_auto_pc_0/dma_design_1_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_design_1_auto_pc_0 || ORIG_REF_NAME==dma_design_1_auto_pc_0} -quiet] -quiet

# XDC: bd/dma_design_1/dma_design_1_ooc.xdc
