# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/yangjiel/edt_tutorial/edt_tutorial.srcs/sources_1/bd/tutorial_bd/ip/tutorial_bd_auto_pc_0/tutorial_bd_auto_pc_0.xci
# IP: The module: 'tutorial_bd_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/yangjiel/edt_tutorial/edt_tutorial.srcs/sources_1/bd/tutorial_bd/ip/tutorial_bd_auto_pc_0/tutorial_bd_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tutorial_bd_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/yangjiel/edt_tutorial/edt_tutorial.srcs/sources_1/bd/tutorial_bd/ip/tutorial_bd_auto_pc_0/tutorial_bd_auto_pc_0.xci
# IP: The module: 'tutorial_bd_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/yangjiel/edt_tutorial/edt_tutorial.srcs/sources_1/bd/tutorial_bd/ip/tutorial_bd_auto_pc_0/tutorial_bd_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tutorial_bd_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
